### ISSUE TITLE
The connections on the pass-if-less-than flow dot file are not correct

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/flow#119]

**Comment by andrewdavidmackenzie** [comment]
<img width="992" alt="screen shot 2018-04-30 at 18 27 21" src="https://user-images.githubusercontent.com/5529132/39438380-433a0548-4ca4-11e8-8903-b22bb8a70085.png">

But according to the description (samples/range/pass-if-less-than.toml):
``` toml
[[connection]]
from = "function/compare/lt"
to = "function/switch/control"
```

There should be an output from compare, called "lt" that is connected to the input of switch.

I assume the absolute route is messing things up.
