### ISSUE TITLE
Include macro for book included verbatim in cargo docs

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/flow#1572]
Source file
add.md

## Add (//flowstdlib/math/add)
Add two inputs to produce a new output
 
### Definition
```toml
{{#include add.toml}}
```

### Include using
```toml
[[process]]
source = "lib://flowstdlib/math/add"
```

See rendered output by cargo docs here
file:///Users/andrew/workspace/flow/target/html/code/doc/flowstdlib/math/add/struct.Add.html
