### ISSUE TITLE
Connnection from an element in an Array initializer

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/flow#743]
Be able to have an array initializer on a sub-flow's Array input, and then within the sub-flow connect from individual elements in that array via array indexing on an array input, as per a function output (get etc)

Will require sub-routes on initializers, treating them more like input.

**Comment by andrewdavidmackenzie** [comment]
This might work now with some recent changes.
Write a test/example that uses it.

**Comment by andrewdavidmackenzie** [comment]
Already works. The mandelbrot example's generate_pixels sub-flow demonstrates this:

```toml
# Sub-flow receives size as array/number input
[[input]]
name = "size"
type = "array/number"

# Connect from individual elements via array indexing
from = "input/size/0"  # width
from = "input/size/1"  # height
```

Mandelbrot compiles and runs correctly with this pattern.
