### ISSUE TITLE
Fix type required for connecting to subroute

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/flow#747]
in array-input test flow

```toml
flow = "subflow"

[[input]]
name = "array_input"
type = "String"

[[process]]
source = "lib://flowruntime/stdio/stdout"

[[connection]]
from = "input/array_input/1"
to = "stdout"
```

the connection type only works correctly if 
```[[input]]
name = "array_input"
type = "String"
```
is String.

When in actual fact the input type is `Array/String`

This isn't a big problem for on connection from that input within the flow, but could be for others that may want the whole connection, or s differently types subroute of the input struct

this is due to the "array_order" in the OutputCOnnection not being calculated correctly (Types is not propogated when selecting a sub-route)

A workaround is to specify output where array originates as Generic, but commenting out:
#type = "Array/Number"
in parse_args.toml
